// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vps.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TelemetryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VpsId     string  `protobuf:"bytes,1,opt,name=vps_id,json=vpsId,proto3" json:"vps_id,omitempty"`
	CpuUsage  float32 `protobuf:"fixed32,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	RamUsage  float32 `protobuf:"fixed32,3,opt,name=ram_usage,json=ramUsage,proto3" json:"ram_usage,omitempty"`
	RamTotal  float32 `protobuf:"fixed32,4,opt,name=ram_total,json=ramTotal,proto3" json:"ram_total,omitempty"`
	DiskUsage float32 `protobuf:"fixed32,5,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	NetTx     float32 `protobuf:"fixed32,6,opt,name=net_tx,json=netTx,proto3" json:"net_tx,omitempty"`
	NetRx     float32 `protobuf:"fixed32,7,opt,name=net_rx,json=netRx,proto3" json:"net_rx,omitempty"`
	Timestamp int64   `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *TelemetryRequest) Reset()         { *x = TelemetryRequest{} }
func (x *TelemetryRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *TelemetryRequest) ProtoMessage()  {}
func (x *TelemetryRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *TelemetryRequest) GetName() string { return "TelemetryRequest" }

func (x *TelemetryRequest) GetVpsId() string     { if x != nil { return x.VpsId }; return "" }
func (x *TelemetryRequest) GetCpuUsage() float32  { if x != nil { return x.CpuUsage }; return 0 }
func (x *TelemetryRequest) GetRamUsage() float32  { if x != nil { return x.RamUsage }; return 0 }
func (x *TelemetryRequest) GetRamTotal() float32  { if x != nil { return x.RamTotal }; return 0 }
func (x *TelemetryRequest) GetDiskUsage() float32 { if x != nil { return x.DiskUsage }; return 0 }
func (x *TelemetryRequest) GetNetTx() float32     { if x != nil { return x.NetTx }; return 0 }
func (x *TelemetryRequest) GetNetRx() float32     { if x != nil { return x.NetRx }; return 0 }
func (x *TelemetryRequest) GetTimestamp() int64    { if x != nil { return x.Timestamp }; return 0 }

type TelemetryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *TelemetryResponse) Reset()         { *x = TelemetryResponse{} }
func (x *TelemetryResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *TelemetryResponse) ProtoMessage()  {}
func (x *TelemetryResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *TelemetryResponse) GetSuccess() bool    { if x != nil { return x.Success }; return false }
func (x *TelemetryResponse) GetMessage() string  { if x != nil { return x.Message }; return "" }

type ShellMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VpsId string `protobuf:"bytes,1,opt,name=vps_id,json=vpsId,proto3" json:"vps_id,omitempty"`
	Data  []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ShellMessage) Reset()         { *x = ShellMessage{} }
func (x *ShellMessage) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *ShellMessage) ProtoMessage()  {}
func (x *ShellMessage) ProtoReflect() protoreflect.Message { return nil }
func (x *ShellMessage) GetVpsId() string { if x != nil { return x.VpsId }; return "" }
func (x *ShellMessage) GetData() []byte  { if x != nil { return x.Data }; return nil }

type CommandRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VpsId          string `protobuf:"bytes,1,opt,name=vps_id,json=vpsId,proto3" json:"vps_id,omitempty"`
	Command        string `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	TimeoutSeconds int32  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
}

func (x *CommandRequest) Reset()         { *x = CommandRequest{} }
func (x *CommandRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *CommandRequest) ProtoMessage()  {}
func (x *CommandRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *CommandRequest) GetVpsId() string          { if x != nil { return x.VpsId }; return "" }
func (x *CommandRequest) GetCommand() string         { if x != nil { return x.Command }; return "" }
func (x *CommandRequest) GetTimeoutSeconds() int32   { if x != nil { return x.TimeoutSeconds }; return 0 }

type CommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Output  string `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *CommandResponse) Reset()         { *x = CommandResponse{} }
func (x *CommandResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *CommandResponse) ProtoMessage()  {}
func (x *CommandResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *CommandResponse) GetSuccess() bool   { if x != nil { return x.Success }; return false }
func (x *CommandResponse) GetOutput() string  { if x != nil { return x.Output }; return "" }

type DirRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VpsId string `protobuf:"bytes,1,opt,name=vps_id,json=vpsId,proto3" json:"vps_id,omitempty"`
	Path  string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *DirRequest) Reset()         { *x = DirRequest{} }
func (x *DirRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *DirRequest) ProtoMessage()  {}
func (x *DirRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *DirRequest) GetVpsId() string { if x != nil { return x.VpsId }; return "" }
func (x *DirRequest) GetPath() string  { if x != nil { return x.Path }; return "" }

type FileItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDir bool   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size  int64  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *FileItem) Reset()         { *x = FileItem{} }
func (x *FileItem) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *FileItem) ProtoMessage()  {}
func (x *FileItem) ProtoReflect() protoreflect.Message { return nil }
func (x *FileItem) GetName() string  { if x != nil { return x.Name }; return "" }
func (x *FileItem) GetIsDir() bool   { if x != nil { return x.IsDir }; return false }
func (x *FileItem) GetSize() int64   { if x != nil { return x.Size }; return 0 }

type DirResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool        `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Files   []*FileItem `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	Error   string      `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DirResponse) Reset()         { *x = DirResponse{} }
func (x *DirResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *DirResponse) ProtoMessage()  {}
func (x *DirResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *DirResponse) GetSuccess() bool      { if x != nil { return x.Success }; return false }
func (x *DirResponse) GetFiles() []*FileItem { if x != nil { return x.Files }; return nil }
func (x *DirResponse) GetError() string      { if x != nil { return x.Error }; return "" }

type FileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VpsId string `protobuf:"bytes,1,opt,name=vps_id,json=vpsId,proto3" json:"vps_id,omitempty"`
	Path  string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *FileRequest) Reset()         { *x = FileRequest{} }
func (x *FileRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *FileRequest) ProtoMessage()  {}
func (x *FileRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *FileRequest) GetVpsId() string { if x != nil { return x.VpsId }; return "" }
func (x *FileRequest) GetPath() string  { if x != nil { return x.Path }; return "" }

type FileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Error   string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *FileResponse) Reset()         { *x = FileResponse{} }
func (x *FileResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *FileResponse) ProtoMessage()  {}
func (x *FileResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *FileResponse) GetSuccess() bool   { if x != nil { return x.Success }; return false }
func (x *FileResponse) GetContent() []byte { if x != nil { return x.Content }; return nil }
func (x *FileResponse) GetError() string   { if x != nil { return x.Error }; return "" }

type WriteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VpsId   string `protobuf:"bytes,1,opt,name=vps_id,json=vpsId,proto3" json:"vps_id,omitempty"`
	Path    string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Content []byte `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *WriteRequest) Reset()         { *x = WriteRequest{} }
func (x *WriteRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *WriteRequest) ProtoMessage()  {}
func (x *WriteRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *WriteRequest) GetVpsId() string   { if x != nil { return x.VpsId }; return "" }
func (x *WriteRequest) GetPath() string    { if x != nil { return x.Path }; return "" }
func (x *WriteRequest) GetContent() []byte { if x != nil { return x.Content }; return nil }

type WriteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *WriteResponse) Reset()         { *x = WriteResponse{} }
func (x *WriteResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *WriteResponse) ProtoMessage()  {}
func (x *WriteResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *WriteResponse) GetSuccess() bool { if x != nil { return x.Success }; return false }
func (x *WriteResponse) GetError() string { if x != nil { return x.Error }; return "" }

type ScreenshotRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VpsId     string `protobuf:"bytes,1,opt,name=vps_id,json=vpsId,proto3" json:"vps_id,omitempty"`
	ImageData []byte `protobuf:"bytes,2,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
}

func (x *ScreenshotRequest) Reset()         { *x = ScreenshotRequest{} }
func (x *ScreenshotRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *ScreenshotRequest) ProtoMessage()  {}
func (x *ScreenshotRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *ScreenshotRequest) GetVpsId() string     { if x != nil { return x.VpsId }; return "" }
func (x *ScreenshotRequest) GetImageData() []byte { if x != nil { return x.ImageData }; return nil }

type ScreenshotResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *ScreenshotResponse) Reset()         { *x = ScreenshotResponse{} }
func (x *ScreenshotResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *ScreenshotResponse) ProtoMessage()  {}
func (x *ScreenshotResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *ScreenshotResponse) GetSuccess() bool { if x != nil { return x.Success }; return false }

type HeartbeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VpsId     string `protobuf:"bytes,1,opt,name=vps_id,json=vpsId,proto3" json:"vps_id,omitempty"`
	Timestamp int64  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *HeartbeatRequest) Reset()         { *x = HeartbeatRequest{} }
func (x *HeartbeatRequest) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *HeartbeatRequest) ProtoMessage()  {}
func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message { return nil }
func (x *HeartbeatRequest) GetVpsId() string     { if x != nil { return x.VpsId }; return "" }
func (x *HeartbeatRequest) GetTimestamp() int64  { if x != nil { return x.Timestamp }; return 0 }

type HeartbeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *HeartbeatResponse) Reset()         { *x = HeartbeatResponse{} }
func (x *HeartbeatResponse) String() string { return protoimpl.X.MessageStringOf(x) }
func (x *HeartbeatResponse) ProtoMessage()  {}
func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message { return nil }
func (x *HeartbeatResponse) GetSuccess() bool { if x != nil { return x.Success }; return false }

// Ensure unused imports are referenced
var (
	_ = reflect.TypeOf
	_ = sync.Mutex{}
)
