// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: vps.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VpsId         string                 `protobuf:"bytes,1,opt,name=vps_id,json=vpsId,proto3" json:"vps_id,omitempty"`
	CpuUsage      float32                `protobuf:"fixed32,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	RamUsage      float32                `protobuf:"fixed32,3,opt,name=ram_usage,json=ramUsage,proto3" json:"ram_usage,omitempty"`
	RamTotal      float32                `protobuf:"fixed32,4,opt,name=ram_total,json=ramTotal,proto3" json:"ram_total,omitempty"`
	DiskUsage     float32                `protobuf:"fixed32,5,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	NetTx         float32                `protobuf:"fixed32,6,opt,name=net_tx,json=netTx,proto3" json:"net_tx,omitempty"`
	NetRx         float32                `protobuf:"fixed32,7,opt,name=net_rx,json=netRx,proto3" json:"net_rx,omitempty"`
	Timestamp     int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	DiskTotal     float32                `protobuf:"fixed32,9,opt,name=disk_total,json=diskTotal,proto3" json:"disk_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryRequest) Reset() {
	*x = TelemetryRequest{}
	mi := &file_vps_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryRequest) ProtoMessage() {}

func (x *TelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vps_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryRequest.ProtoReflect.Descriptor instead.
func (*TelemetryRequest) Descriptor() ([]byte, []int) {
	return file_vps_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryRequest) GetVpsId() string {
	if x != nil {
		return x.VpsId
	}
	return ""
}

func (x *TelemetryRequest) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *TelemetryRequest) GetRamUsage() float32 {
	if x != nil {
		return x.RamUsage
	}
	return 0
}

func (x *TelemetryRequest) GetRamTotal() float32 {
	if x != nil {
		return x.RamTotal
	}
	return 0
}

func (x *TelemetryRequest) GetDiskUsage() float32 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

func (x *TelemetryRequest) GetNetTx() float32 {
	if x != nil {
		return x.NetTx
	}
	return 0
}

func (x *TelemetryRequest) GetNetRx() float32 {
	if x != nil {
		return x.NetRx
	}
	return 0
}

func (x *TelemetryRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TelemetryRequest) GetDiskTotal() float32 {
	if x != nil {
		return x.DiskTotal
	}
	return 0
}

type TelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryResponse) Reset() {
	*x = TelemetryResponse{}
	mi := &file_vps_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryResponse) ProtoMessage() {}

func (x *TelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vps_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryResponse.ProtoReflect.Descriptor instead.
func (*TelemetryResponse) Descriptor() ([]byte, []int) {
	return file_vps_proto_rawDescGZIP(), []int{1}
}

func (x *TelemetryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TelemetryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ScreenshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VpsId         string                 `protobuf:"bytes,1,opt,name=vps_id,json=vpsId,proto3" json:"vps_id,omitempty"`
	ImageData     []byte                 `protobuf:"bytes,2,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenshotRequest) Reset() {
	*x = ScreenshotRequest{}
	mi := &file_vps_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenshotRequest) ProtoMessage() {}

func (x *ScreenshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vps_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenshotRequest.ProtoReflect.Descriptor instead.
func (*ScreenshotRequest) Descriptor() ([]byte, []int) {
	return file_vps_proto_rawDescGZIP(), []int{2}
}

func (x *ScreenshotRequest) GetVpsId() string {
	if x != nil {
		return x.VpsId
	}
	return ""
}

func (x *ScreenshotRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

type ScreenshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenshotResponse) Reset() {
	*x = ScreenshotResponse{}
	mi := &file_vps_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenshotResponse) ProtoMessage() {}

func (x *ScreenshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vps_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenshotResponse.ProtoReflect.Descriptor instead.
func (*ScreenshotResponse) Descriptor() ([]byte, []int) {
	return file_vps_proto_rawDescGZIP(), []int{3}
}

func (x *ScreenshotResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VpsId         string                 `protobuf:"bytes,1,opt,name=vps_id,json=vpsId,proto3" json:"vps_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	AgentIp       string                 `protobuf:"bytes,3,opt,name=agent_ip,json=agentIp,proto3" json:"agent_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_vps_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vps_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_vps_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetVpsId() string {
	if x != nil {
		return x.VpsId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *HeartbeatRequest) GetAgentIp() string {
	if x != nil {
		return x.AgentIp
	}
	return ""
}

type VpsSettingsMessage struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ScreenshotIntervalSec int32                  `protobuf:"varint,1,opt,name=screenshot_interval_sec,json=screenshotIntervalSec,proto3" json:"screenshot_interval_sec,omitempty"`
	TelemetryIntervalSec  int32                  `protobuf:"varint,2,opt,name=telemetry_interval_sec,json=telemetryIntervalSec,proto3" json:"telemetry_interval_sec,omitempty"`
	RamDiskVisible        bool                   `protobuf:"varint,3,opt,name=ram_disk_visible,json=ramDiskVisible,proto3" json:"ram_disk_visible,omitempty"`
	NetworkVisible        bool                   `protobuf:"varint,4,opt,name=network_visible,json=networkVisible,proto3" json:"network_visible,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *VpsSettingsMessage) Reset() {
	*x = VpsSettingsMessage{}
	mi := &file_vps_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VpsSettingsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VpsSettingsMessage) ProtoMessage() {}

func (x *VpsSettingsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_vps_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VpsSettingsMessage.ProtoReflect.Descriptor instead.
func (*VpsSettingsMessage) Descriptor() ([]byte, []int) {
	return file_vps_proto_rawDescGZIP(), []int{5}
}

func (x *VpsSettingsMessage) GetScreenshotIntervalSec() int32 {
	if x != nil {
		return x.ScreenshotIntervalSec
	}
	return 0
}

func (x *VpsSettingsMessage) GetTelemetryIntervalSec() int32 {
	if x != nil {
		return x.TelemetryIntervalSec
	}
	return 0
}

func (x *VpsSettingsMessage) GetRamDiskVisible() bool {
	if x != nil {
		return x.RamDiskVisible
	}
	return false
}

func (x *VpsSettingsMessage) GetNetworkVisible() bool {
	if x != nil {
		return x.NetworkVisible
	}
	return false
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Settings      *VpsSettingsMessage    `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_vps_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vps_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_vps_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetSettings() *VpsSettingsMessage {
	if x != nil {
		return x.Settings
	}
	return nil
}

type ServerMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*ServerMessage_Exec
	//	*ServerMessage_Listdir
	//	*ServerMessage_Read
	//	*ServerMessage_Write
	//	*ServerMessage_ShellOpen
	//	*ServerMessage_ShellInput
	//	*ServerMessage_ShellClose
	//	*ServerMessage_Refresh
	Body          isServerMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_vps_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_vps_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_vps_proto_rawDescGZIP(), []int{7}
}

func (x *ServerMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ServerMessage) GetBody() isServerMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ServerMessage) GetExec() *CommandRequest {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_Exec); ok {
			return x.Exec
		}
	}
	return nil
}

func (x *ServerMessage) GetListdir() *DirRequest {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_Listdir); ok {
			return x.Listdir
		}
	}
	return nil
}

func (x *ServerMessage) GetRead() *FileRequest {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_Read); ok {
			return x.Read
		}
	}
	return nil
}

func (x *ServerMessage) GetWrite() *WriteRequest {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_Write); ok {
			return x.Write
		}
	}
	return nil
}

func (x *ServerMessage) GetShellOpen() *ShellOpenRequest {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_ShellOpen); ok {
			return x.ShellOpen
		}
	}
	return nil
}

func (x *ServerMessage) GetShellInput() *ShellInputRequest {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_ShellInput); ok {
			return x.ShellInput
		}
	}
	return nil
}

func (x *ServerMessage) GetShellClose() *ShellCloseRequest {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_ShellClose); ok {
			return x.ShellClose
		}
	}
	return nil
}

func (x *ServerMessage) GetRefresh() *RefreshRequest {
	if x != nil {
		if x, ok := x.Body.(*ServerMessage_Refresh); ok {
			return x.Refresh
		}
	}
	return nil
}

type isServerMessage_Body interface {
	isServerMessage_Body()
}

type ServerMessage_Exec struct {
	Exec *CommandRequest `protobuf:"bytes,11,opt,name=exec,proto3,oneof"`
}

type ServerMessage_Listdir struct {
	Listdir *DirRequest `protobuf:"bytes,12,opt,name=listdir,proto3,oneof"`
}

type ServerMessage_Read struct {
	Read *FileRequest `protobuf:"bytes,13,opt,name=read,proto3,oneof"`
}

type ServerMessage_Write struct {
	Write *WriteRequest `protobuf:"bytes,14,opt,name=write,proto3,oneof"`
}

type ServerMessage_ShellOpen struct {
	ShellOpen *ShellOpenRequest `protobuf:"bytes,15,opt,name=shell_open,json=shellOpen,proto3,oneof"`
}

type ServerMessage_ShellInput struct {
	ShellInput *ShellInputRequest `protobuf:"bytes,16,opt,name=shell_input,json=shellInput,proto3,oneof"`
}

type ServerMessage_ShellClose struct {
	ShellClose *ShellCloseRequest `protobuf:"bytes,17,opt,name=shell_close,json=shellClose,proto3,oneof"`
}

type ServerMessage_Refresh struct {
	Refresh *RefreshRequest `protobuf:"bytes,18,opt,name=refresh,proto3,oneof"`
}

func (*ServerMessage_Exec) isServerMessage_Body() {}

func (*ServerMessage_Listdir) isServerMessage_Body() {}

func (*ServerMessage_Read) isServerMessage_Body() {}

func (*ServerMessage_Write) isServerMessage_Body() {}

func (*ServerMessage_ShellOpen) isServerMessage_Body() {}

func (*ServerMessage_ShellInput) isServerMessage_Body() {}

func (*ServerMessage_ShellClose) isServerMessage_Body() {}

func (*ServerMessage_Refresh) isServerMessage_Body() {}

type AgentMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*AgentMessage_Register
	//	*AgentMessage_ExecResult
	//	*AgentMessage_ListdirResult
	//	*AgentMessage_ReadResult
	//	*AgentMessage_WriteResult
	//	*AgentMessage_ShellOpened
	//	*AgentMessage_ShellOutput
	//	*AgentMessage_ShellClosed
	//	*AgentMessage_RefreshAck
	Body          isAgentMessage_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_vps_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_vps_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_vps_proto_rawDescGZIP(), []int{8}
}

func (x *AgentMessage) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AgentMessage) GetBody() isAgentMessage_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *AgentMessage) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentMessage) GetExecResult() *CommandResponse {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_ExecResult); ok {
			return x.ExecResult
		}
	}
	return nil
}

func (x *AgentMessage) GetListdirResult() *DirResponse {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_ListdirResult); ok {
			return x.ListdirResult
		}
	}
	return nil
}

func (x *AgentMessage) GetReadResult() *FileResponse {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_ReadResult); ok {
			return x.ReadResult
		}
	}
	return nil
}

func (x *AgentMessage) GetWriteResult() *WriteResponse {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_WriteResult); ok {
			return x.WriteResult
		}
	}
	return nil
}

func (x *AgentMessage) GetShellOpened() *ShellOpenedResponse {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_ShellOpened); ok {
			return x.ShellOpened
		}
	}
	return nil
}

func (x *AgentMessage) GetShellOutput() *ShellOutput {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_ShellOutput); ok {
			return x.ShellOutput
		}
	}
	return nil
}

func (x *AgentMessage) GetShellClosed() *ShellClosedResponse {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_ShellClosed); ok {
			return x.ShellClosed
		}
	}
	return nil
}

func (x *AgentMessage) GetRefreshAck() *RefreshAck {
	if x != nil {
		if x, ok := x.Body.(*AgentMessage_RefreshAck); ok {
			return x.RefreshAck
		}
	}
	return nil
}

type isAgentMessage_Body interface {
	isAgentMessage_Body()
}

type AgentMessage_Register struct {
	Register *RegisterRequest `protobuf:"bytes,10,opt,name=register,proto3,oneof"`
}

type AgentMessage_ExecResult struct {
	ExecResult *CommandResponse `protobuf:"bytes,11,opt,name=exec_result,json=execResult,proto3,oneof"`
}

type AgentMessage_ListdirResult struct {
	ListdirResult *DirResponse `protobuf:"bytes,12,opt,name=listdir_result,json=listdirResult,proto3,oneof"`
}

type AgentMessage_ReadResult struct {
	ReadResult *FileResponse `protobuf:"bytes,13,opt,name=read_result,json=readResult,proto3,oneof"`
}

type AgentMessage_WriteResult struct {
	WriteResult *WriteResponse `protobuf:"bytes,14,opt,name=write_result,json=writeResult,proto3,oneof"`
}

type AgentMessage_ShellOpened struct {
	ShellOpened *ShellOpenedResponse `protobuf:"bytes,15,opt,name=shell_opened,json=shellOpened,proto3,oneof"`
}

type AgentMessage_ShellOutput struct {
	ShellOutput *ShellOutput `protobuf:"bytes,16,opt,name=shell_output,json=shellOutput,proto3,oneof"`
}

type AgentMessage_ShellClosed struct {
	ShellClosed *ShellClosedResponse `protobuf:"bytes,17,opt,name=shell_closed,json=shellClosed,proto3,oneof"`
}

type AgentMessage_RefreshAck struct {
	RefreshAck *RefreshAck `protobuf:"bytes,18,opt,name=refresh_ack,json=refreshAck,proto3,oneof"`
}

func (*AgentMessage_Register) isAgentMessage_Body() {}

func (*AgentMessage_ExecResult) isAgentMessage_Body() {}

func (*AgentMessage_ListdirResult) isAgentMessage_Body() {}

func (*AgentMessage_ReadResult) isAgentMessage_Body() {}

func (*AgentMessage_WriteResult) isAgentMessage_Body() {}

func (*AgentMessage_ShellOpened) isAgentMessage_Body() {}

func (*AgentMessage_ShellOutput) isAgentMessage_Body() {}

func (*AgentMessage_ShellClosed) isAgentMessage_Body() {}

func (*AgentMessage_RefreshAck) isAgentMessage_Body() {}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VpsId         string                 `protobuf:"bytes,1,opt,name=vps_id,json=vpsId,proto3" json:"vps_id,omitempty"`
	AgentIp       string                 `protobuf:"bytes,2,opt,name=agent_ip,json=agentIp,proto3" json:"agent_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_vps_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vps_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_vps_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterRequest) GetVpsId() string {
	if x != nil {
		return x.VpsId
	}
	return ""
}

func (x *RegisterRequest) GetAgentIp() string {
	if x != nil {
		return x.AgentIp
	}
	return ""
}

type CommandRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VpsId          string                 `protobuf:"bytes,1,opt,name=vps_id,json=vpsId,proto3" json:"vps_id,omitempty"`
	Command        string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CommandRequest) Reset() {
	*x = CommandRequest{}
	mi := &file_vps_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandRequest) ProtoMessage() {}

func (x *CommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vps_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandRequest.ProtoReflect.Descriptor instead.
func (*CommandRequest) Descriptor() ([]byte, []int) {
	return file_vps_proto_rawDescGZIP(), []int{10}
}

func (x *CommandRequest) GetVpsId() string {
	if x != nil {
		return x.VpsId
	}
	return ""
}

func (x *CommandRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *CommandRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type CommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
	mi := &file_vps_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vps_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResponse.ProtoReflect.Descriptor instead.
func (*CommandResponse) Descriptor() ([]byte, []int) {
	return file_vps_proto_rawDescGZIP(), []int{11}
}

func (x *CommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type DirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VpsId         string                 `protobuf:"bytes,1,opt,name=vps_id,json=vpsId,proto3" json:"vps_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirRequest) Reset() {
	*x = DirRequest{}
	mi := &file_vps_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirRequest) ProtoMessage() {}

func (x *DirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vps_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirRequest.ProtoReflect.Descriptor instead.
func (*DirRequest) Descriptor() ([]byte, []int) {
	return file_vps_proto_rawDescGZIP(), []int{12}
}

func (x *DirRequest) GetVpsId() string {
	if x != nil {
		return x.VpsId
	}
	return ""
}

func (x *DirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FileItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileItem) Reset() {
	*x = FileItem{}
	mi := &file_vps_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileItem) ProtoMessage() {}

func (x *FileItem) ProtoReflect() protoreflect.Message {
	mi := &file_vps_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileItem.ProtoReflect.Descriptor instead.
func (*FileItem) Descriptor() ([]byte, []int) {
	return file_vps_proto_rawDescGZIP(), []int{13}
}

func (x *FileItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileItem) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileItem) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type DirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Files         []*FileItem            `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirResponse) Reset() {
	*x = DirResponse{}
	mi := &file_vps_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirResponse) ProtoMessage() {}

func (x *DirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vps_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirResponse.ProtoReflect.Descriptor instead.
func (*DirResponse) Descriptor() ([]byte, []int) {
	return file_vps_proto_rawDescGZIP(), []int{14}
}

func (x *DirResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DirResponse) GetFiles() []*FileItem {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *DirResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VpsId         string                 `protobuf:"bytes,1,opt,name=vps_id,json=vpsId,proto3" json:"vps_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_vps_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vps_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_vps_proto_rawDescGZIP(), []int{15}
}

func (x *FileRequest) GetVpsId() string {
	if x != nil {
		return x.VpsId
	}
	return ""
}

func (x *FileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileResponse) Reset() {
	*x = FileResponse{}
	mi := &file_vps_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResponse) ProtoMessage() {}

func (x *FileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vps_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResponse.ProtoReflect.Descriptor instead.
func (*FileResponse) Descriptor() ([]byte, []int) {
	return file_vps_proto_rawDescGZIP(), []int{16}
}

func (x *FileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FileResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VpsId         string                 `protobuf:"bytes,1,opt,name=vps_id,json=vpsId,proto3" json:"vps_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_vps_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vps_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_vps_proto_rawDescGZIP(), []int{17}
}

func (x *WriteRequest) GetVpsId() string {
	if x != nil {
		return x.VpsId
	}
	return ""
}

func (x *WriteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_vps_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vps_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_vps_proto_rawDescGZIP(), []int{18}
}

func (x *WriteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WriteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ShellOpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	VpsId         string                 `protobuf:"bytes,2,opt,name=vps_id,json=vpsId,proto3" json:"vps_id,omitempty"`
	Shell         string                 `protobuf:"bytes,3,opt,name=shell,proto3" json:"shell,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellOpenRequest) Reset() {
	*x = ShellOpenRequest{}
	mi := &file_vps_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellOpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellOpenRequest) ProtoMessage() {}

func (x *ShellOpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vps_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellOpenRequest.ProtoReflect.Descriptor instead.
func (*ShellOpenRequest) Descriptor() ([]byte, []int) {
	return file_vps_proto_rawDescGZIP(), []int{19}
}

func (x *ShellOpenRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ShellOpenRequest) GetVpsId() string {
	if x != nil {
		return x.VpsId
	}
	return ""
}

func (x *ShellOpenRequest) GetShell() string {
	if x != nil {
		return x.Shell
	}
	return ""
}

type ShellOpenedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellOpenedResponse) Reset() {
	*x = ShellOpenedResponse{}
	mi := &file_vps_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellOpenedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellOpenedResponse) ProtoMessage() {}

func (x *ShellOpenedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vps_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellOpenedResponse.ProtoReflect.Descriptor instead.
func (*ShellOpenedResponse) Descriptor() ([]byte, []int) {
	return file_vps_proto_rawDescGZIP(), []int{20}
}

func (x *ShellOpenedResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ShellOpenedResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ShellOpenedResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ShellInputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellInputRequest) Reset() {
	*x = ShellInputRequest{}
	mi := &file_vps_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellInputRequest) ProtoMessage() {}

func (x *ShellInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vps_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellInputRequest.ProtoReflect.Descriptor instead.
func (*ShellInputRequest) Descriptor() ([]byte, []int) {
	return file_vps_proto_rawDescGZIP(), []int{21}
}

func (x *ShellInputRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ShellInputRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ShellOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellOutput) Reset() {
	*x = ShellOutput{}
	mi := &file_vps_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellOutput) ProtoMessage() {}

func (x *ShellOutput) ProtoReflect() protoreflect.Message {
	mi := &file_vps_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellOutput.ProtoReflect.Descriptor instead.
func (*ShellOutput) Descriptor() ([]byte, []int) {
	return file_vps_proto_rawDescGZIP(), []int{22}
}

func (x *ShellOutput) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ShellOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ShellCloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellCloseRequest) Reset() {
	*x = ShellCloseRequest{}
	mi := &file_vps_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellCloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellCloseRequest) ProtoMessage() {}

func (x *ShellCloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vps_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellCloseRequest.ProtoReflect.Descriptor instead.
func (*ShellCloseRequest) Descriptor() ([]byte, []int) {
	return file_vps_proto_rawDescGZIP(), []int{23}
}

func (x *ShellCloseRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ShellClosedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShellClosedResponse) Reset() {
	*x = ShellClosedResponse{}
	mi := &file_vps_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShellClosedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShellClosedResponse) ProtoMessage() {}

func (x *ShellClosedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vps_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShellClosedResponse.ProtoReflect.Descriptor instead.
func (*ShellClosedResponse) Descriptor() ([]byte, []int) {
	return file_vps_proto_rawDescGZIP(), []int{24}
}

func (x *ShellClosedResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VpsId         string                 `protobuf:"bytes,1,opt,name=vps_id,json=vpsId,proto3" json:"vps_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_vps_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vps_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_vps_proto_rawDescGZIP(), []int{25}
}

func (x *RefreshRequest) GetVpsId() string {
	if x != nil {
		return x.VpsId
	}
	return ""
}

type RefreshAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshAck) Reset() {
	*x = RefreshAck{}
	mi := &file_vps_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshAck) ProtoMessage() {}

func (x *RefreshAck) ProtoReflect() protoreflect.Message {
	mi := &file_vps_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshAck.ProtoReflect.Descriptor instead.
func (*RefreshAck) Descriptor() ([]byte, []int) {
	return file_vps_proto_rawDescGZIP(), []int{26}
}

func (x *RefreshAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RefreshAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_vps_proto protoreflect.FileDescriptor

const file_vps_proto_rawDesc = "" +
	"\n" +
	"\tvps.proto\x12\x03vps\"\x8a\x02\n" +
	"\x10TelemetryRequest\x12\x15\n" +
	"\x06vps_id\x18\x01 \x01(\tR\x05vpsId\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x02R\bcpuUsage\x12\x1b\n" +
	"\tram_usage\x18\x03 \x01(\x02R\bramUsage\x12\x1b\n" +
	"\tram_total\x18\x04 \x01(\x02R\bramTotal\x12\x1d\n" +
	"\n" +
	"disk_usage\x18\x05 \x01(\x02R\tdiskUsage\x12\x15\n" +
	"\x06net_tx\x18\x06 \x01(\x02R\x05netTx\x12\x15\n" +
	"\x06net_rx\x18\a \x01(\x02R\x05netRx\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"disk_total\x18\t \x01(\x02R\tdiskTotal\"G\n" +
	"\x11TelemetryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"I\n" +
	"\x11ScreenshotRequest\x12\x15\n" +
	"\x06vps_id\x18\x01 \x01(\tR\x05vpsId\x12\x1d\n" +
	"\n" +
	"image_data\x18\x02 \x01(\fR\timageData\".\n" +
	"\x12ScreenshotResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"b\n" +
	"\x10HeartbeatRequest\x12\x15\n" +
	"\x06vps_id\x18\x01 \x01(\tR\x05vpsId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x19\n" +
	"\bagent_ip\x18\x03 \x01(\tR\aagentIp\"\xd5\x01\n" +
	"\x12VpsSettingsMessage\x126\n" +
	"\x17screenshot_interval_sec\x18\x01 \x01(\x05R\x15screenshotIntervalSec\x124\n" +
	"\x16telemetry_interval_sec\x18\x02 \x01(\x05R\x14telemetryIntervalSec\x12(\n" +
	"\x10ram_disk_visible\x18\x03 \x01(\bR\x0eramDiskVisible\x12'\n" +
	"\x0fnetwork_visible\x18\x04 \x01(\bR\x0enetworkVisible\"b\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x123\n" +
	"\bsettings\x18\x02 \x01(\v2\x17.vps.VpsSettingsMessageR\bsettings\"\xc0\x03\n" +
	"\rServerMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12)\n" +
	"\x04exec\x18\v \x01(\v2\x13.vps.CommandRequestH\x00R\x04exec\x12+\n" +
	"\alistdir\x18\f \x01(\v2\x0f.vps.DirRequestH\x00R\alistdir\x12&\n" +
	"\x04read\x18\r \x01(\v2\x10.vps.FileRequestH\x00R\x04read\x12)\n" +
	"\x05write\x18\x0e \x01(\v2\x11.vps.WriteRequestH\x00R\x05write\x126\n" +
	"\n" +
	"shell_open\x18\x0f \x01(\v2\x15.vps.ShellOpenRequestH\x00R\tshellOpen\x129\n" +
	"\vshell_input\x18\x10 \x01(\v2\x16.vps.ShellInputRequestH\x00R\n" +
	"shellInput\x129\n" +
	"\vshell_close\x18\x11 \x01(\v2\x16.vps.ShellCloseRequestH\x00R\n" +
	"shellClose\x12/\n" +
	"\arefresh\x18\x12 \x01(\v2\x13.vps.RefreshRequestH\x00R\arefreshB\x06\n" +
	"\x04body\"\xb5\x04\n" +
	"\fAgentMessage\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x122\n" +
	"\bregister\x18\n" +
	" \x01(\v2\x14.vps.RegisterRequestH\x00R\bregister\x127\n" +
	"\vexec_result\x18\v \x01(\v2\x14.vps.CommandResponseH\x00R\n" +
	"execResult\x129\n" +
	"\x0elistdir_result\x18\f \x01(\v2\x10.vps.DirResponseH\x00R\rlistdirResult\x124\n" +
	"\vread_result\x18\r \x01(\v2\x11.vps.FileResponseH\x00R\n" +
	"readResult\x127\n" +
	"\fwrite_result\x18\x0e \x01(\v2\x12.vps.WriteResponseH\x00R\vwriteResult\x12=\n" +
	"\fshell_opened\x18\x0f \x01(\v2\x18.vps.ShellOpenedResponseH\x00R\vshellOpened\x125\n" +
	"\fshell_output\x18\x10 \x01(\v2\x10.vps.ShellOutputH\x00R\vshellOutput\x12=\n" +
	"\fshell_closed\x18\x11 \x01(\v2\x18.vps.ShellClosedResponseH\x00R\vshellClosed\x122\n" +
	"\vrefresh_ack\x18\x12 \x01(\v2\x0f.vps.RefreshAckH\x00R\n" +
	"refreshAckB\x06\n" +
	"\x04body\"C\n" +
	"\x0fRegisterRequest\x12\x15\n" +
	"\x06vps_id\x18\x01 \x01(\tR\x05vpsId\x12\x19\n" +
	"\bagent_ip\x18\x02 \x01(\tR\aagentIp\"j\n" +
	"\x0eCommandRequest\x12\x15\n" +
	"\x06vps_id\x18\x01 \x01(\tR\x05vpsId\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12'\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\x05R\x0etimeoutSeconds\"C\n" +
	"\x0fCommandResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\"7\n" +
	"\n" +
	"DirRequest\x12\x15\n" +
	"\x06vps_id\x18\x01 \x01(\tR\x05vpsId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"I\n" +
	"\bFileItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"b\n" +
	"\vDirResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\x05files\x18\x02 \x03(\v2\r.vps.FileItemR\x05files\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"8\n" +
	"\vFileRequest\x12\x15\n" +
	"\x06vps_id\x18\x01 \x01(\tR\x05vpsId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"X\n" +
	"\fFileResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"S\n" +
	"\fWriteRequest\x12\x15\n" +
	"\x06vps_id\x18\x01 \x01(\tR\x05vpsId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\"?\n" +
	"\rWriteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"^\n" +
	"\x10ShellOpenRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06vps_id\x18\x02 \x01(\tR\x05vpsId\x12\x14\n" +
	"\x05shell\x18\x03 \x01(\tR\x05shell\"d\n" +
	"\x13ShellOpenedResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"F\n" +
	"\x11ShellInputRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"@\n" +
	"\vShellOutput\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"2\n" +
	"\x11ShellCloseRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"4\n" +
	"\x13ShellClosedResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"'\n" +
	"\x0eRefreshRequest\x12\x15\n" +
	"\x06vps_id\x18\x01 \x01(\tR\x05vpsId\"?\n" +
	"\n" +
	"RefreshAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x15\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x91\x02\n" +
	"\x0eBackendService\x12B\n" +
	"\x0fStreamTelemetry\x12\x15.vps.TelemetryRequest\x1a\x16.vps.TelemetryResponse(\x01\x12C\n" +
	"\x10UploadScreenshot\x12\x16.vps.ScreenshotRequest\x1a\x17.vps.ScreenshotResponse\x12:\n" +
	"\tHeartbeat\x12\x15.vps.HeartbeatRequest\x1a\x16.vps.HeartbeatResponse\x12:\n" +
	"\rStreamAgentIO\x12\x11.vps.AgentMessage\x1a\x12.vps.ServerMessage(\x010\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_vps_proto_rawDescOnce sync.Once
	file_vps_proto_rawDescData []byte
)

func file_vps_proto_rawDescGZIP() []byte {
	file_vps_proto_rawDescOnce.Do(func() {
		file_vps_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vps_proto_rawDesc), len(file_vps_proto_rawDesc)))
	})
	return file_vps_proto_rawDescData
}

var file_vps_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_vps_proto_goTypes = []any{
	(*TelemetryRequest)(nil),    // 0: vps.TelemetryRequest
	(*TelemetryResponse)(nil),   // 1: vps.TelemetryResponse
	(*ScreenshotRequest)(nil),   // 2: vps.ScreenshotRequest
	(*ScreenshotResponse)(nil),  // 3: vps.ScreenshotResponse
	(*HeartbeatRequest)(nil),    // 4: vps.HeartbeatRequest
	(*VpsSettingsMessage)(nil),  // 5: vps.VpsSettingsMessage
	(*HeartbeatResponse)(nil),   // 6: vps.HeartbeatResponse
	(*ServerMessage)(nil),       // 7: vps.ServerMessage
	(*AgentMessage)(nil),        // 8: vps.AgentMessage
	(*RegisterRequest)(nil),     // 9: vps.RegisterRequest
	(*CommandRequest)(nil),      // 10: vps.CommandRequest
	(*CommandResponse)(nil),     // 11: vps.CommandResponse
	(*DirRequest)(nil),          // 12: vps.DirRequest
	(*FileItem)(nil),            // 13: vps.FileItem
	(*DirResponse)(nil),         // 14: vps.DirResponse
	(*FileRequest)(nil),         // 15: vps.FileRequest
	(*FileResponse)(nil),        // 16: vps.FileResponse
	(*WriteRequest)(nil),        // 17: vps.WriteRequest
	(*WriteResponse)(nil),       // 18: vps.WriteResponse
	(*ShellOpenRequest)(nil),    // 19: vps.ShellOpenRequest
	(*ShellOpenedResponse)(nil), // 20: vps.ShellOpenedResponse
	(*ShellInputRequest)(nil),   // 21: vps.ShellInputRequest
	(*ShellOutput)(nil),         // 22: vps.ShellOutput
	(*ShellCloseRequest)(nil),   // 23: vps.ShellCloseRequest
	(*ShellClosedResponse)(nil), // 24: vps.ShellClosedResponse
	(*RefreshRequest)(nil),      // 25: vps.RefreshRequest
	(*RefreshAck)(nil),          // 26: vps.RefreshAck
}
var file_vps_proto_depIdxs = []int32{
	5,  // 0: vps.HeartbeatResponse.settings:type_name -> vps.VpsSettingsMessage
	10, // 1: vps.ServerMessage.exec:type_name -> vps.CommandRequest
	12, // 2: vps.ServerMessage.listdir:type_name -> vps.DirRequest
	15, // 3: vps.ServerMessage.read:type_name -> vps.FileRequest
	17, // 4: vps.ServerMessage.write:type_name -> vps.WriteRequest
	19, // 5: vps.ServerMessage.shell_open:type_name -> vps.ShellOpenRequest
	21, // 6: vps.ServerMessage.shell_input:type_name -> vps.ShellInputRequest
	23, // 7: vps.ServerMessage.shell_close:type_name -> vps.ShellCloseRequest
	25, // 8: vps.ServerMessage.refresh:type_name -> vps.RefreshRequest
	9,  // 9: vps.AgentMessage.register:type_name -> vps.RegisterRequest
	11, // 10: vps.AgentMessage.exec_result:type_name -> vps.CommandResponse
	14, // 11: vps.AgentMessage.listdir_result:type_name -> vps.DirResponse
	16, // 12: vps.AgentMessage.read_result:type_name -> vps.FileResponse
	18, // 13: vps.AgentMessage.write_result:type_name -> vps.WriteResponse
	20, // 14: vps.AgentMessage.shell_opened:type_name -> vps.ShellOpenedResponse
	22, // 15: vps.AgentMessage.shell_output:type_name -> vps.ShellOutput
	24, // 16: vps.AgentMessage.shell_closed:type_name -> vps.ShellClosedResponse
	26, // 17: vps.AgentMessage.refresh_ack:type_name -> vps.RefreshAck
	13, // 18: vps.DirResponse.files:type_name -> vps.FileItem
	0,  // 19: vps.BackendService.StreamTelemetry:input_type -> vps.TelemetryRequest
	2,  // 20: vps.BackendService.UploadScreenshot:input_type -> vps.ScreenshotRequest
	4,  // 21: vps.BackendService.Heartbeat:input_type -> vps.HeartbeatRequest
	8,  // 22: vps.BackendService.StreamAgentIO:input_type -> vps.AgentMessage
	1,  // 23: vps.BackendService.StreamTelemetry:output_type -> vps.TelemetryResponse
	3,  // 24: vps.BackendService.UploadScreenshot:output_type -> vps.ScreenshotResponse
	6,  // 25: vps.BackendService.Heartbeat:output_type -> vps.HeartbeatResponse
	7,  // 26: vps.BackendService.StreamAgentIO:output_type -> vps.ServerMessage
	23, // [23:27] is the sub-list for method output_type
	19, // [19:23] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_vps_proto_init() }
func file_vps_proto_init() {
	if File_vps_proto != nil {
		return
	}
	file_vps_proto_msgTypes[7].OneofWrappers = []any{
		(*ServerMessage_Exec)(nil),
		(*ServerMessage_Listdir)(nil),
		(*ServerMessage_Read)(nil),
		(*ServerMessage_Write)(nil),
		(*ServerMessage_ShellOpen)(nil),
		(*ServerMessage_ShellInput)(nil),
		(*ServerMessage_ShellClose)(nil),
		(*ServerMessage_Refresh)(nil),
	}
	file_vps_proto_msgTypes[8].OneofWrappers = []any{
		(*AgentMessage_Register)(nil),
		(*AgentMessage_ExecResult)(nil),
		(*AgentMessage_ListdirResult)(nil),
		(*AgentMessage_ReadResult)(nil),
		(*AgentMessage_WriteResult)(nil),
		(*AgentMessage_ShellOpened)(nil),
		(*AgentMessage_ShellOutput)(nil),
		(*AgentMessage_ShellClosed)(nil),
		(*AgentMessage_RefreshAck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vps_proto_rawDesc), len(file_vps_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vps_proto_goTypes,
		DependencyIndexes: file_vps_proto_depIdxs,
		MessageInfos:      file_vps_proto_msgTypes,
	}.Build()
	File_vps_proto = out.File
	file_vps_proto_goTypes = nil
	file_vps_proto_depIdxs = nil
}
